export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS';
export const GET_ARTICLES_START = 'GET_ARTICLES_START';
export const GET_ARTICLES_FAILURE = 'GET_ARTICLES_FAILURE';
export const CLEAR_ARTICLES = 'CLEAR_ARTICLES';